reader:
  loading_strategy: split
  data_type: transaction
  reading_method: local
  rating_type: implicit
  labels:
    user_id_label: user_id
    item_id_label: item_id
    rating_label: rating
    timestamp_label: timestamp
  dtypes:
    user_id_type: int64
    item_id_type: int64
    timestamp_type: int64
  split:
    local_path: data/yandex_30000/legacy_global_split_raw
    ext: .csv
    sep: ","
    header: false

writer:
  dataset_name: yandex_30000_legacy_split_raw
  writing_method: local
  local_experiment_path: experiments/yandex/legacy_split_raw/
  results:
    sep: ","
    ext: .csv
  recommendation:
    sep: ","
    ext: .csv
    header: true
    k: 50
    user_label: user_id
    item_label: item_id

evaluation:
  top_k: [10, 20, 50]
  metrics: [nDCG, Precision, Recall, HitRate]
  validation_metric: nDCG@10
  batch_size: 512

models:
  BERT4Rec_gts:
    embedding_size: 128
    n_layers: 3
    n_heads: 2
    inner_size: 512
    dropout_prob: 0.2
    attn_dropout_prob: 0.2
    mask_prob: 0.2
    reg_weight: 0.0
    weight_decay: 0
    batch_size: 128
    epochs: 10000
    learning_rate: 0.001
    max_seq_len: 150
    early_stopping:
      monitor: "score"
      patience: 500
      grace_period: 50
      min_delta: 0.0001
    optimization:
      strategy: grid
      properties:
        mode: max
        seed: 42
      cpu_per_trial: 12
      gpu_per_trial: 1

general:
  device: cuda
  custom_models: ["warprec_recjpq"]
