name: PR-Linting

on:
  pull_request:
    branches: ["*"]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          install-pyg: 'true'

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
