name: Release

on:
  push:
    branches:
      - main

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          install-pyg: 'true'
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

  release:
    needs: lint-check
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN_WARPREC }}

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          install-pyg: 'false'

      - name: Install Python Semantic Release
        run: pip install python-semantic-release

      - name: Git Configuration
        run: |
          git config user.name "github-actions [bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Python Semantic Release (Version & Push)
        id: psr
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN_WARPREC }}
        run: |
          semantic-release version
          if [ -f ".release_version" ] || git describe --tags --exact-match HEAD >/dev/null 2>&1; then
            echo "released=true" >> $GITHUB_OUTPUT
          else
            echo "released=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Package
        if: steps.psr.outputs.released == 'true'
        run: poetry build

      - name: Publish to GitHub Release
        if: steps.psr.outputs.released == 'true'
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN_WARPREC }}
        run: semantic-release publish

      - name: Publish to PyPI
        if: steps.psr.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
