name: Tests

on:
  pull_request:
    branches: ["*"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run tests
        run: poetry run pytest tests/ -q
